### ISSUE TITLE
Processing feedback for GUI

### ISSUE THREAD

**Issue by mdholbrook** [mdholbrook/bme590final#54]
It would be nice to have some feedback on the GUI side for what's happening (generally) on the server. Let me know when you find out if the POST request is blocking or not. Then we can start thinking about how to let the user know when their files have been downloaded.

**Comment by mdholbrook** [comment]
I added a box in the GUI to display image information and error messages. The server should send the following information: 
* Image timestamp
* Processing time
* Image dimensions

I've coded these values to be stored as the following:

https://github.com/mdholbrook/bme590final/blob/e9ef485adfefbe5826961b8f8f6533c9b4e2c86f/GUI/main_window.py#L269-L272

**Comment by mdholbrook** [comment]
I'll take a look at it and upload a fix. You've merged your changes?

**Comment by mdholbrook** [comment]
I've fixed the "show2" error and added some better error handling in #63.

**Comment by abg28** [comment]
It appears to me that the GUI stalls while the server runs through its endpoints, preventing any kind of overloading.  For example, try selecting foosball.jpg from the TestImages folder, and processing it with the "Histogram" option (this takes extra time because the histogram method must flatten color images before they can be processed).  I could also be interpreting the stalling completely wrong.

**Comment by mdholbrook** [comment]
I keep getting this error: "A key is missing from the user data dictionary."

I'm starting to think that the data isn't being sent. I can't get print statements to work on the server.
